# Generated by Django 6.0.6 on 2026-06-28 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('total_amount_cents', models.PositiveIntegerField()),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('custom', 'Custom')], default='equal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting confirmation'), ('paid', 'Paid')], default='pending', max_length=25)),
                ('proof_url', models.URLField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'installments',
            },
        ),
    ]
