# Generated by Django 6.0.6 on 2026-06-30 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='created_by',
            field=models.ForeignKey(db_column='dsp_criado_por_id', on_delete=django.db.models.deletion.CASCADE, related_name='debts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='group',
            field=models.ForeignKey(db_column='dsp_grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='groups.group'),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_by',
            field=models.ForeignKey(db_column='dsp_pago_por_id', on_delete=django.db.models.deletion.CASCADE, related_name='debts_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installment',
            name='debt',
            field=models.ForeignKey(db_column='pcl_despesa_id', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='debts.debt'),
        ),
        migrations.AddField(
            model_name='installment',
            name='debtor',
            field=models.ForeignKey(db_column='pcl_devedor_id', on_delete=django.db.models.deletion.CASCADE, related_name='installments_owed', to=settings.AUTH_USER_MODEL),
        ),
    ]
