# Generated by Django 5.2.4 on 2026-06-30 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_installment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'awaiting_confirmation'])), fields=['status'], name='pcl_status_ativo_idx'),
        ),
    ]
