# Generated by Django 6.0.6 on 2026-06-28 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_link', to='debts.installment')),
            ],
            options={
                'db_table': 'charge_links',
            },
        ),
    ]
