# Generated by Django 6.0.6 on 2026-06-30 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.UUIDField(db_column='cpv_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(db_column='cpv_arquivo_url')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='cpv_enviado_em')),
                ('parcela', models.ForeignKey(db_column='cpv_parcela_id', on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='debts.installment')),
                ('uploaded_by', models.ForeignKey(db_column='cpv_enviado_por_id', on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comprovantes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
