# Generated by Django 6.0.6 on 2026-06-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.BigAutoField(db_column='mgp_id', primary_key=True, serialize=False),
        ),
    ]
