# Generated by Django 5.2.4 on 2026-07-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='adicionado_por',
            field=models.ForeignKey(blank=True, db_column='mgp_adicionado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_adicionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente_confirmacao', 'Aguardando confirmação'), ('pendente_registro', 'Aguardando cadastro')], db_column='mgp_status', default='ativo', max_length=25),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(blank=True, db_column='mgp_usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContatoPendente',
            fields=[
                ('id', models.BigAutoField(db_column='ctp_id', primary_key=True, serialize=False)),
                ('phone', models.CharField(db_column='ctp_telefone', max_length=20, unique=True)),
                ('name', models.CharField(db_column='ctp_nome', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='ctp_criado_em')),
                ('criado_por', models.ForeignKey(db_column='ctp_criado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_pendentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contatos_pendentes',
            },
        ),
        migrations.AddField(
            model_name='groupmember',
            name='contato_pendente',
            field=models.ForeignKey(blank=True, db_column='mgp_contato_pendente_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='groups.contatopendente'),
        ),
    ]
