# Generated by Django 5.2.4 on 2026-07-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groupmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='display_name',
            field=models.CharField(blank=True, db_column='mgp_nome_exibicao', max_length=150),
        ),
    ]
