# Generated by Django 6.0.6 on 2026-06-30 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeLink',
            fields=[
                ('id', models.UUIDField(db_column='lnk_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_column='lnk_token', default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(db_column='lnk_expira_em')),
                ('used_at', models.DateTimeField(blank=True, db_column='lnk_usado_em', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='lnk_criado_em')),
                ('installment', models.OneToOneField(db_column='lnk_parcela_id', on_delete=django.db.models.deletion.CASCADE, related_name='charge_link', to='debts.installment')),
            ],
            options={
                'db_table': 'links_cobranca',
            },
        ),
    ]
