# Generated by Django 5.2.4 on 2026-07-19 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_comprovante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acerto',
            fields=[
                ('id', models.UUIDField(db_column='act_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Aguardando confirmação'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado')], db_column='act_status', db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='act_criado_em')),
                ('resolved_at', models.DateTimeField(blank=True, db_column='act_resolvido_em', null=True)),
                ('de', models.ForeignKey(db_column='act_de_id', on_delete=django.db.models.deletion.CASCADE, related_name='acertos_propostos', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(db_column='act_para_id', on_delete=django.db.models.deletion.CASCADE, related_name='acertos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acertos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['para', 'status'], name='acerto_para_status_idx')],
            },
        ),
    ]
