# Generated by Django 5.2.4 on 2026-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_add_parcelas_partial_index'),
        ('payments', '0003_acerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='acerto',
            name='parcelas',
            field=models.ManyToManyField(blank=True, db_table='acerto_parcelas', related_name='acertos', to='debts.installment'),
        ),
    ]
