# Generated by Django 5.2.4 on 2026-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_installment_paid_via'),
        ('payments', '0004_acerto_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='acerto',
            name='parcelas_quitadas',
            field=models.ManyToManyField(blank=True, db_table='acerto_parcelas_quitadas', related_name='quitacoes_acerto', to='debts.installment'),
        ),
    ]
