# Generated by Django 6.0.6 on 2026-09-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_acerto_parcelas_quitadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='arquivo',
            field=models.FileField(blank=True, db_column='cpv_arquivo', null=True, upload_to='comprovantes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='file_url',
            field=models.URLField(blank=True, db_column='cpv_arquivo_url', null=True),
        ),
    ]
