# Generated by Django 6.0.6 on 2026-06-30 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoLida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.CharField(db_column='ntf_evento_id', max_length=60)),
                ('lida_em', models.DateTimeField(auto_now_add=True, db_column='ntf_lida_em')),
                ('usuario', models.ForeignKey(db_column='ntf_usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacoes_lidas',
                'unique_together': {('usuario', 'evento_id')},
            },
        ),
    ]
