# Generated by Django 6.0.6 on 2026-06-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notificacaolida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaolida',
            name='id',
            field=models.BigAutoField(db_column='ntf_id', primary_key=True, serialize=False),
        ),
    ]
