# Generated by Django 5.2.4 on 2026-07-02 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_unique_username_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_column='prc_code_hash', max_length=64)),
                ('expires_at', models.DateTimeField(db_column='prc_expires_at')),
                ('used', models.BooleanField(db_column='prc_usado', default=False)),
                ('attempts', models.PositiveSmallIntegerField(db_column='prc_tentativas', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='prc_criado_em')),
                ('user', models.ForeignKey(db_column='prc_usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codigos_recuperacao',
                'indexes': [models.Index(fields=['user', 'used', 'expires_at'], name='codigos_rec_prc_usu_3d117c_idx')],
            },
        ),
    ]
