# Generated by Django 5.2.4 on 2026-07-04 21:04

import apps.users.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rotate_totp_encryption_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trusteddevice',
            new_name='dispositivo_trd_usu_f77a69_idx',
            old_name='dispositivos_trd_idx',
        ),
        migrations.AlterField(
            model_name='twofactorconfig',
            name='secret',
            field=apps.users.fields.EncryptedCharField(db_column='tfa_secret', max_length=512),
        ),
    ]
