# Generated by Django 5.2.4 on 2026-07-05 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_dispositivos_trd_idx_dispositivo_trd_usu_f77a69_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login_ok', 'Login bem-sucedido'), ('login_fail', 'Login falhou'), ('totp_ok', 'TOTP verificado'), ('totp_fail', 'TOTP falhou'), ('totp_locked', 'TOTP bloqueado'), ('2fa_on', '2FA ativado'), ('2fa_off', '2FA desativado'), ('pwd_reset', 'Senha redefinida'), ('token_refresh', 'Token atualizado')], db_column='aud_evento', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, db_column='aud_ip', null=True)),
                ('user_agent', models.CharField(blank=True, db_column='aud_user_agent', max_length=256)),
                ('detail', models.JSONField(blank=True, db_column='aud_detalhe', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='aud_criado_em')),
                ('user', models.ForeignKey(blank=True, db_column='aud_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='auditoria_usr_idx'), models.Index(fields=['event', '-created_at'], name='auditoria_evt_idx'), models.Index(fields=['ip', '-created_at'], name='auditoria_ip_idx')],
            },
        ),
    ]
