# Generated by Django 5.2.4 on 2026-07-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(db_column='usr_tel_verificado', default=False),
        ),
        # 1) Torna nullable (sem unique ainda)
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_column='usr_telefone', max_length=20, null=True),
        ),
        # 2) Converte strings vazias para NULL (safe agora que a coluna aceita NULL)
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('users', 'User').objects.filter(phone='').update(phone=None),
            reverse_code=migrations.RunPython.noop,
        ),
        # 3) Aplica unique constraint (sem conflito pois '' já virou NULL)
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_column='usr_telefone', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SmsVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_column='sms_code_hash', max_length=64)),
                ('expires_at', models.DateTimeField(db_column='sms_expires_at')),
                ('used', models.BooleanField(db_column='sms_usado', default=False)),
                ('attempts', models.PositiveSmallIntegerField(db_column='sms_tentativas', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='sms_criado_em')),
                ('user', models.OneToOneField(db_column='sms_usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='sms_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verificacoes_sms',
            },
        ),
    ]
