# Generated by Django 5.2.4 on 2026-07-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_phone_verified_alter_user_phone_smsverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('login_ok', 'Login bem-sucedido'), ('login_fail', 'Login falhou'), ('totp_ok', 'TOTP verificado'), ('totp_fail', 'TOTP falhou'), ('totp_locked', 'TOTP bloqueado'), ('2fa_on', '2FA ativado'), ('2fa_off', '2FA desativado'), ('pwd_reset', 'Senha redefinida'), ('token_refresh', 'Token atualizado'), ('debt_updated', 'Dívida editada'), ('debt_deleted', 'Dívida excluída')], db_column='aud_evento', max_length=20),
        ),
    ]
