# Generated by Django 6.0.6 on 2026-06-30 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(db_column='grp_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='grp_nome', max_length=120)),
                ('emoji', models.CharField(blank=True, db_column='grp_emoji', max_length=8)),
                ('archived', models.BooleanField(db_column='grp_arquivado', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='grp_criado_em')),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Membro')], db_column='mgp_papel', default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='mgp_entrou_em')),
            ],
            options={
                'db_table': 'membros_grupo',
            },
        ),
    ]
