# Generated by Django 6.0.6 on 2026-06-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupmember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='archived',
            field=models.BooleanField(db_column='grp_arquivado', db_index=True, default=False),
        ),
    ]
