# Generated by Django 6.0.6 on 2026-06-30 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(db_column='dsp_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='dsp_descricao', max_length=255)),
                ('total_amount_cents', models.PositiveIntegerField(db_column='dsp_total_centavos')),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('custom', 'Custom')], db_column='dsp_tipo_divisao', default='equal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dsp_criado_em')),
            ],
            options={
                'db_table': 'despesas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(db_column='pcl_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField(db_column='pcl_valor_centavos')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_confirmation', 'Aguardando confirmação'), ('paid', 'Pago')], db_column='pcl_status', default='pending', max_length=25)),
                ('paid_at', models.DateTimeField(blank=True, db_column='pcl_pago_em', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_column='pcl_confirmado_em', null=True)),
            ],
            options={
                'db_table': 'parcelas',
            },
        ),
    ]
