# Generated by Django 6.0.6 on 2026-06-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('awaiting_confirmation', 'Aguardando confirmação'), ('paid', 'Pago')], db_column='pcl_status', db_index=True, default='pending', max_length=25),
        ),
    ]
