# Generated by Django 5.2.4 on 2026-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_add_parcelas_partial_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid_via',
            field=models.CharField(choices=[('payment', 'Pagamento'), ('compensation', 'Compensação')], db_column='pcl_forma_quitacao', default='payment', max_length=12),
        ),
    ]
