# Generated by Django 5.2.4 on 2026-07-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_installment_paid_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='ultimo_lembrete_em',
            field=models.DateTimeField(blank=True, db_column='pcl_ultimo_lembrete_em', null=True),
        ),
    ]
