# Generated by Django 6.0.6 on 2026-09-12 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_installment_ultimo_lembrete_em'),
        ('groups', '0006_groupmember_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='debtor_contato',
            field=models.ForeignKey(blank=True, db_column='pcl_devedor_contato_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='groups.contatopendente'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='debtor',
            field=models.ForeignKey(blank=True, db_column='pcl_devedor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments_owed', to=settings.AUTH_USER_MODEL),
        ),
    ]
